structure(list(url = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/no_hit/cids/JSON", 
    status_code = 404L, headers = structure(list(date = "Fri, 04 Nov 2022 15:21:42 GMT", 
        server = "Apache", `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        `referrer-policy` = "origin-when-cross-origin", `content-security-policy` = "upgrade-insecure-requests", 
        `cache-control` = "private", expires = "Fri, 04 Nov 2022 23:21:42 GMT", 
        `ncbi-phid` = "95B6C07E3652E0610000000000000001.m_1", 
        `ncbi-sid` = "95B6C07E3652E061_0000SID", `x-throttling-control` = "Request Count status: Green (0%), Request Time status: Green (0%), Service status: Green (10%)", 
        `content-type` = "application/json", `set-cookie` = "REDACTED", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `x-ua-compatible` = "IE=Edge", `x-xss-protection` = "1; mode=block", 
        `access-control-allow-origin` = "*", `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Fri, 04 Nov 2022 15:21:42 GMT", 
            server = "Apache", `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
            `referrer-policy` = "origin-when-cross-origin", `content-security-policy` = "upgrade-insecure-requests", 
            `cache-control` = "private", expires = "Fri, 04 Nov 2022 23:21:42 GMT", 
            `ncbi-phid` = "95B6C07E3652E0610000000000000001.m_1", 
            `ncbi-sid` = "95B6C07E3652E061_0000SID", `x-throttling-control` = "Request Count status: Green (0%), Request Time status: Green (0%), Service status: Green (10%)", 
            `content-type` = "application/json", `set-cookie` = "REDACTED", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `x-ua-compatible` = "IE=Edge", `x-xss-protection` = "1; mode=block", 
            `access-control-allow-origin` = "*", `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = ".nih.gov", 
        flag = TRUE, path = "/", secure = FALSE, expiration = structure(1699111302, class = c("POSIXct", 
        "POSIXt")), name = "ncbi_sid", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\n  \"Fault\": {\n    \"Code\": \"PUGREST.NotFound\",\n    \"Message\": \"No CID found\",\n    \"Details\": [\n      \"No CID found that matches the given name\"\n    ]\n  }\n}\n"), 
    date = structure(1667575302, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.023503, 
    connect = 0.12591, pretransfer = 0.347843, starttransfer = 0.523624, 
    total = 0.525532)), class = "response")
